export const images = {
  bitcoinIsland: `/images/bitcoin-island.webp`,
  blogPreview: `/images/blog-preview.webp`,
  dogma: `/images/dogma.webp`,
  dvadesetJedan: `/images/dvadeset-jedan.webp`,
  magicInternetMoney: `/images/magic-internet-money.webp`,
  meetupCover: `/images/meetup-cover.webp`,
  meetup: `/images/meetup.webp`,
  player: `/images/player.webp`,
  hero1: `/images/hero_6.webp`,
  hero2: `/images/hero_2.webp`,
  hero3: `/images/hero_3.webp`,
  hero4: `/images/hero_7.webp`,
  hero5: `/images/hero_5.webp`,
  "bullishcase-featured": `/images/content/bullishcase-featured.jpg`,
  "bitcoin-nasil-oldurulur": `/images/content/bitcoin-nasil-oldurulur.jpg`,
  "bitcoini-bes-yasindaymisim-gibi-anlat": `/images/content/bitcoini-bes-yasindaymisim-gibi-anlat.png`,
  "bitcoinehosgeldiniz": `/images/content/bitcoinehosgeldiniz.jpeg`,
  "ne-kadar-bitcoin": `/images/content/ne-kadar-bitcoin.jpg`,
  "bitcoin-merkeziyetsizdir": `/images/content/bitcoin-merkeziyetsizdir.png`,
  "bitcoin-yasaklanamaz": `/images/content/bitcoin-yasaklanamaz.png`,
  "bitcoin-suna-benzer": `/images/content/bitcoin-suna-benzer.png`,
  "bitcoinin-fiat-para-birimlerine-ve-bisikletlere-gore-karsilasirmasi": `/images/content/yarisma.png`,
  "sevgili-ailem": `/images/content/dear-family.jpeg`,
  "ozgurce-konusmak": `/images/content/ozgurce-konusmak.jpg`,
  "kimse-bitcoini-anlamiyor": `/images/content/kimse-bitcoini-anlamiyor.png`,
  "bitcoin-gelistirmenin-taosu": `/images/content/bitcoin-gelistirmenin-taosu.png`,
} as const;
